### ISSUE TITLE
vector matrix from extract_feature( )

### ISSUE THREAD

**Issue by jumfina** [abhijeet3922/Speaker-identification-using-GMMs#1]
extract_feature( ) produces a matrix of vectors of dimensions 399 by 40. As I understand, 40 is the 20 MFCC+ 20 Delta MFCC features of a single speaker file. Could you say what is contained in the 399 dimension?

**Comment by zsn900503** [comment]
399 should be your No. of frames. You basically separate the audio into small frames, and you got 20 MFCC + 20 DMFCC from each frame
